#!/usr/bin/env bash
# Build the paper. Assumes paper/data/* has been generated by analyze.ts.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if [[ ! -f data/hit-40000.dat ]]; then
	echo "error: paper/data not generated. Run:" >&2
	echo "  node --import tsx scripts/cache-research/analyze.ts --in <run.jsonl> --outdir paper/data" >&2
	exit 1
fi

pdflatex -interaction=nonstopmode -halt-on-error paper.tex >/dev/null
bibtex paper >/dev/null 2>&1 || true
pdflatex -interaction=nonstopmode -halt-on-error paper.tex >/dev/null
pdflatex -interaction=nonstopmode -halt-on-error paper.tex >/dev/null
echo "built paper/paper.pdf ($(du -h paper.pdf | cut -f1))"
